[package]
name = "sleigh2rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sleigh-rs = { "path"= "../sleigh-rs" }
sleigh4rust = { "path"= "../sleigh4rust" }
quote = "1"
bitvec = "1"
proc-macro2 = "1"
indexmap = "1.9"
ethnum = "1"
